### ISSUE TITLE
【提案】OS連動のダークモード設定

### ISSUE THREAD

**Issue by sckemu** [tsukumijima/TVRemotePlus#2]
いつも便利に使わせていただいております。
ダークモードのデフォルト設定をOSと連動させるのはどうでしょうか。

CSSの[prefers-color-scheme](https://developer.mozilla.org/ja/docs/Web/CSS/@media/prefers-color-scheme)が利用できそうです。

**Comment by tsukumijima** [comment]
提案ありがとうございます。
システムの設定をダークモードにしていない場合でもダークモードに切り替えられるように（私がまさにそのパターンです）他の設定と一緒に設定状態を Cookie に保存するようにしているのですが、初期値を prefer-color-scheme に合わせて変えるくらいならできるかもしれません。検討します。

**Comment by tsukumijima** [comment]
f235dc2aa67d7834a43e26f0b1d0b518c78843b7 にて対応しました。ありがとうございました！
