### ISSUE TITLE
プルリクの方針についての質問

### ISSUE THREAD

**Issue by xtne6f** [tsukumijima/TVRemotePlus#4]
セキュリティ関連のプルリクエストをこちらに投げたいのですが、事前に内容の通知(DM等)を望まれますか？
ご希望の場合、私はtwitterを使っていないため、できればtwitter以外の手段(GPGの公開鍵での暗号化など)を提案してもらえると幸いです。
直接プルリクで構わない場合は、リリース直前の公開が望ましいと思うので、都合の良いタイミングをお聞かせください。
よろしくお願いします。

**Comment by tsukumijima** [comment]
セキュリティ関連ですか…。わざわざ丁寧に連絡していただいて恐縮です。ありがとうございます。

TVRemotePlus は（見れば分かる通り）プログラミング初心者の頃にフレームワークなしで設計と呼べるものを何もせずに書いてしまったものに無理やり機能追加等をしていった結果、私自身もはやなぜ動いているのか分からない部分があるほどにスパゲッティコードと化してしまっています。
元々は個人的な習作で、ここまで多機能にする事を想定して作っていなかったのが大きいのですが…。時間がたっぷりあればモダンな構成にして書き直したいくらいですが、そこまでの時間がなくどうにか保守しているのが現状です。
常に外部からの攻撃に晒される Web サービスと異なり基本はローカルネットワーク内のみで動作するということもあって、セキュリティ周りはほとんど考慮していないというのが正直なところです。

…閑話休題。
そこまでクリティカルな脆弱性ではないと思いたいですが、念のため事前に内容を通知していただけるのなら助かります。
連絡手段は Twitter をやってらっしゃらないとの事なので、メールでどうでしょうか。下のコメントにあるメールアドレス宛に送っていただけると助かります（このコメントに👍をつけていただいたタイミングで下のコメントは削除します）。よろしくお願いします。

**Comment by tsukumijima** [comment]
`tsukumijima@gmail.com`

**Comment by xtne6f** [comment]
了解です。のちほどコミットの内容と簡単な攻撃例を添付してメールします。
